apiVersion: v1
kind: Service
metadata:
  labels:
    service: kong
    wicked: "true"
  name: kong
spec:
  ports:
  - name: "admin"
    port: 8001
    protocol: TCP
  selector:
    service: kong
---
apiVersion: v1
kind: Service
metadata:
  labels:
    service: kong
  name: kong-gw
spec:
  ports:
  - name: "gateway"
    port: 8000
    protocol: TCP
  selector:
    service: kong
