apiVersion: v1
kind: Service
metadata:
  labels:
    service: portal-api
    wicked: "true"
  name: portal-api
spec:
  ports:
  - name: "3001"
    port: 3001
    protocol: TCP
    targetPort: 3001
  selector:
    service: portal-api
