apiVersion: v1
kind: Service
metadata:
  labels:
    service: portal-mailer
    wicked: "true"
  name: portal-mailer
spec:
  ports:
  - name: "3003"
    port: 3003
    protocol: TCP
    targetPort: 3003
  selector:
    service: portal-mailer