apiVersion: v1
kind: Service
metadata:
  labels:
    service: portal-chatbot
    wicked: "true"
  name: portal-chatbot
spec:
  ports:
  - name: "3004"
    port: 3004
    protocol: TCP
    targetPort: 3004
  selector:
    service: portal-chatbot
