apiVersion: v1
kind: Service
metadata:
  labels:
    service: portal
    wicked: "true"
  name: portal
spec:
  ports:
  - name: "3000"
    port: 3000
    protocol: TCP
    targetPort: 3000
  selector:
    service: portal