apiVersion: v1
kind: Service
metadata:
  labels:
    service: portal-kong-adapter
    wicked: "true"
  name: portal-kong-adapter
spec:
  ports:
  - name: "3002"
    port: 3002
    protocol: TCP
    targetPort: 3002
  selector:
    service: portal-kong-adapter