apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: kong-database
spec:
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        service: kong-database
        wicked: "true"
    spec:
      containers:
      - env:
        - name: POSTGRES_USER
          value: kong
        - name: POSTGRES_PASSWORD
          value: kong
        image: postgres:9.4
        name: kong-database
        ports:
        - name: "psql"
          containerPort: 5432
          protocol: TCP
        volumeMounts:
        - mountPath: /var/lib/postgresql/data
          name: kong-db-data
      restartPolicy: Always
      volumes:
      - name: kong-db-data
        persistentVolumeClaim:
          claimName: persistent-data-postgres
